#!/bin/bash

umask 077

prunefs='devfs devpts iso9660 ncpfs NFS nfs proc smbfs supermount udf usbdevfs vfat unknown'

#export FINDOPTIONS=-L
export PRUNEPATHS=
#="/tmp /usr/tmp /var/tmp /home/*/tmp /home/*/private/.private
#export PRUNEPATHS="/home/*/local/Incomplete "
export PRUNEREGEX='^/.*/\([Cc]ache\|RECYCLER\|Incomplete\|spool\|[Tt]e?mp\|\.?private\)*$'

if [ "$1" = "--dry-run" ]; then
    dry_run=true
    shift
fi

echoVar () {
    local var
    for var; do
        echo
        eval echo -E $var=\\\'\$$var\\\'
    done
}

if [ -n "$CYGROOT" ]; then
    PRUNEPATHS+="/c/cygwin /d /e /f /g /home/*/LOCALS~1/Temp /c/WINDOWS/Temp /c/Documents\ and\ Settings /proc /c/System\ Volume\ Information "

    # Ignore targets of directory links in the root directory
    PRUNEPATHS+=`find -H / -maxdepth 1 -type l -xtype d -printf '%l '`
fi

echoVar FINDOPTIONS PRUNEPATHS PRUNEREGEX
echo
cmd="/bin/updatedb ${prunefs:+--prunefs='$prunefs'}"
echo $cmd

if [ -z "$dry_run" ]; then
    eval $cmd 2>&1 | grep -v "File system loop detected; .*/cygwin' is"
fi
