# -*- outline-regexp: "^[\t ]*#[\t ]+[^=]\\|^# +\\|^[\t ]*..." -*-

# ****** WARNING: This file is automatically generated. ****** 
# ******          Edits may be overwritten at any time! ****** 

# Built:	Wed Sep 22 22:19:18 PDT 2004
# By:  	pschaaf@copernicus
# For:
#    host     = generic      shell    = csh       
#    uname    = UNKN         term     = xterm     

if ( $?prompt ) then
set interactive=true
endif
alias 'prependToVar' 'setenv \!:1 \!:2${\!:1}'
alias 'appendToVar' 'setenv \!:1 ${\!:1}\!:2'
alias 'echoVar' 'echo -n \$; (env | grep -i "^\!^=") || (set | grep -i "^\!^[^A-Za-z0-9]") || (echo \!^=)'
alias 'member' 'echo - ${\!:2} - | grep " \!:1 " >&/dev/null'
alias 'rmpath' 'echo rmpath not yet implemented for csh'
set path=($path)
# set echo
# ======== umask
# This umask gives these access permissions:
# user=rwx, group=rx, others=rx
umask 22


# ======= Debugging Code

# rm -f $HOME/test
# 
# echo '----------''$?_' >> $HOME/test
# if ($?_) then
#   echo $_ >> $HOME/test
# endif
# 
# echo '----------''$?0' >> $HOME/test
# if ($?0) then
#   echo $0 >> $HOME/test
# endif
# 
# echo '----------'tty   >> $HOME/test
# tty   >> $HOME/test
# 
# echo '----------'set   >> $HOME/test
# set   >> $HOME/test
# 
# echo '----------'env   >> $HOME/test
# env   >> $HOME/test
# ======== Fix the Path
# echo a path without double slashes, or empty or relative paths

# ======== Terminal Settings
if ( -e TERM ) then
if ( "$TERM" == "screen" ) then
setenv TERM xterm
endif
endif
if ( $?interactive ) then
true  stty susp '^Z' eol '^-' werase '^W' eof '^D' start '^Q' eol2 '^-' erase '^?' time '0' intr '^C' rprnt '^R' stop '^S' min '1' lnext '^V' flush '^O' quit '^\\' kill '^U' 
endif
# ======== Colors
if ( $?interactive ) then
if ( "$TERM" != "emacs" ) then
setenv USE_COLOR true
endif
endif
# ======== Unalias
unalias l la ll ls lsd rm d s p rd 2>/dev/null
# ======== Default Settings
if (! $?USER) setenv USER $LOGNAME
if (! $?LD_LIBRARY_PATH) setenv LD_LIBRARY_PATH /lib
setenv UID `id | sed 's/^uid=\([0-9][0-9]*\).*/\1/g'`
# ======== Shell Options

set    ignoreeof
unset autologout
set    noclobber
unset  notify


limit coredumpsize 0
set      rmstar
unset    printexitvalue
# ======== Completion, Hashing
if ( $?interactive ) then

set filec
setenv FIGNORE '(.class .o \~ .stackdump dump.txt nohup.out)'
endif
# ======== Zsh Compinstall
# ======== Cd, Dirs, Popd, Pushd
if ( $?interactive ) then
alias 'cd' 'pushd'

set    pushdsilent  pushdtohome
alias 'pushd' 'pushd \!* > /dev/null'
set symlinks ignore
endif
# ======== Shell History
if ( $?interactive ) then
set histdup=all
set history=1000 savehist
set histlit
endif
# ======== Aliases
if ( $?interactive ) then
alias 'any_alias' 'alias \!*'
alias 'basename' 'collect command\ basename'
alias 'bye' 'exit'

alias 'dirname' 'collect command\ dirname'
alias df >& /dev/null || alias 'df' 'df -h'
alias du >& /dev/null || alias 'du' 'du -h'
alias 'ECHO' 'echo'
alias 'EHCO' 'echo'
alias 'ehco' 'echo'
alias 'freshen' 'source ~/'
alias 'igrep' 'grep -i'
alias 'less' '/usr/bin/less'
setenv PAGER /usr/bin/less
alias 'rm' 'rm -i'
alias 'which-command' 'path'
alias 'whoami' 'who am i | awk "{print \$1}"'
endif
# ======== Clearcase Aliases
# ======== ls Aliases
setenv LS_BIN ls
alias 'l' '$LS_BIN'
setenv LA_FLAGS '-AF'
setenv LS_FLAGS '-F'
setenv LL_FLAGS '-Fl'
alias 'la' 'ls -AF'
alias 'ls' 'ls -F'
alias 'll' 'ls -Fl'
alias 'lr' 'ls -R'
alias 'lla' 'la -l'
alias 'llt' 'll -rt'
alias 'lld' 'll  \!* | grep  "/$\\|^$\\|^[^ ][^ ]*$"'
alias 'lltt' 'llt \!* | grep "date +%b.%d"'

# ======== Path Functions
if ( $?interactive ) then
alias 'classpath' 'echo Examining \$CLASSPATH; echo; echoList $CLASSPATH \!*'
alias 'libpath' 'echo Examining \$\$LD_LIBRARY_PATH; echo; echoList $LD_LIBRARY_PATH \!*'
alias 'manpath' 'echo Examining \$MANPATH; echo; echoList ${MANPATH:-`man -w`} \!*'
alias 'path' '; echo; echoList $path \!*'
endif
alias 'appendClasspath' 'eval setenv CLASSPATH "`$HOME/bin/echoMaybeAppendPath.sh 1 $CLASSPATH \!*`"'
alias 'prependClasspath' 'setenv CLASSPATH "`$HOME/bin/echoMaybeAppendPath.sh 0 $CLASSPATH \!*`"'
alias 'appendLibpath' 'eval setenv LD_LIBRARY_PATH "`$HOME/bin/echoMaybeAppendPath.sh 1 $LD_LIBRARY_PATH \!*`"'
alias 'prependLibpath' 'setenv LD_LIBRARY_PATH "`$HOME/bin/echoMaybeAppendPath.sh 0 $LD_LIBRARY_PATH \!*`"'
alias 'appendManpath' 'eval setenv MANPATH "`$HOME/bin/echoMaybeAppendPath.sh 1 $MANPATH \!*`"'
alias 'prependManpath' 'setenv MANPATH "`$HOME/bin/echoMaybeAppendPath.sh 0 $MANPATH \!*`"'
alias 'appendPath' 'eval setenv path "`$HOME/bin/echoMaybeAppendPath.sh 1 $path \!*`"'
alias 'prependPath' 'setenv path "`$HOME/bin/echoMaybeAppendPath.sh 0 $path \!*`"'

# ======== Functions
alias 'cdl' 'cd \!*; ls'

alias 'collect' 'set cmd=$1; shift; echo \!* | xargs -n 1 $cmd'

alias 'echoList' 'echo \!:1 | tr : \\012 | cat -n'
alias 'edit' '$EDITOR \!* &'
alias 'grep' 'if [ "$1" = "--color=never" ]; then shift; fi; false \!*'


alias 'makealias' "quote | /bin/sed 's/^/alias \!:1 /' \!:2*"

alias 'quote' "/bin/sed -e 's/\!/\\\!/g' -e 's/'\\''/'\\'\\\\'\\''/g' -e 's/^/'\''/' -e 's/"\$"/'\''/'"
# Save script args in variable to allow access inside script




alias 'wcat' 'which_meta cat'

alias 'wedit' 'which_meta $PAGER'
alias 'whence' 'alias \!*; sh -c "type \!*"'
alias 'wless' 'which_meta $PAGER'
# ======== ssh
# ======== Remote sessions
if ( $?CONNECTION ) then
set CONNECTION_END=' '
endif
# ======== Environment and Shell Variables
setenv BROWSER mozclient
setenv CTVIEW "[1;35m`$HOME/bin/getCTView`[0m"
setenv EDITOR vi
setenv ENSCRIPT '-M letter'
set EXIT=exit
setenv FCEDIT vi
setenv LESS ' --RAW-CONTROL-CHARS --hilite-unread --ignore-case --jump-target=2 --no-init --quit-at-eof --quit-if-one-screen --status-column -Ps%dt/%D ?f%f::STDIN:$'
setenv LIBPATH_NAME LD_LIBRARY_PATH
if (! $?SCREENDIR) setenv SCREENDIR $HOME/tmp
if ( $?SCRIPT_ARGS ) then
setenv SCRIPTING_MSG '[cc] '
endif
setenv SHELL csh
setenv UNAME UNKN
if ( $?EDITOR ) then
setenv VISUAL $EDITOR
endif
setenv VERSANT_ROOT /usr/local/versant/vds605
# ======== Printers
setenv PRINTER lj1
# ======== Cygwin Path
# ======== Function Keys
if ( ! $?inScreen ) then
endif
# ======== Cursor Keys
# ======== Other Extra Keys
# ======== Macro Keys
# ======== Lesskey
setenv LESSKEY /home/pschaaf/.less_generic
# ======== Classpath
# ======== Path
prependPath /bin /usr/bin /usr/local/bin
appendPath /sbin /usr/sbin /usr/local/sbin $HOME/bin $HOME/bin/usr-local-bin
# ======== Library Path
appendLibpath /lib /usr/lib $HOME/lib
# ======== Prompt
if ( $?interactive ) then
setenv HOST_COLOR "[1;41;37m"
if ( "$UID" == "0" ) then
prependToVar HOST_COLOR "[41m### "
endif
set dirs=
switch ($TERM)
case emacs:
	
setenv prompt "$HOST_COLOR${USER}@copernicus
\\
! c$ "
alias 'chpwd' 'set dirs=`dirs`; set dirs=${dirs[1]}; echo "`date +%H:%M` $dirs"'

breaksw
case default:
	
setenv prompt "$HOST_COLOR${USER}@copernicus
[0m\\
! c$ "
alias 'chpwd' 'set dirs=`dirs`; set dirs=${dirs[1]}; echo "`date +%H:%M` [1;33m$dirs[0m"'

breaksw
endsw
setenv PROMPT_NOCOLOR setenv prompt "$HOST_COLOR${USER}@copernicus
\\
! c$ "
chpwd
endif
# ======== Cygwin
# ======== Manpath

# Move this heredoc around in the file to temporarily disable sections
# of code. Make sure to keep the opening tag first, and the closing tag
# against the left margin on a line by itself. Don't forget that any
# edits are lost if this file is re-generated.
# : <<DEBUG_NO_EXEC
# DEBUG_NO_EXEC
# 

# Used packages: 
#	less	vi
