#!/bin/sh

# $Source: e:/MyDocuments/cvsroot/lib/sh/dirs_status,v $
# $Revision: 1.1 $
# $Date: 2004/02/27 02:05:07 $
# $Author: pschaaf $
# $State: Exp $
# $Name:  $

COLORED_USER_HOSTNAME="`shortUname --colorString $LOGNAME@$HOSTNAME`"

dirs_status () {
    case $#
    in
        0)
            printf "%s $COLORED_USER_HOSTNAME " `date +%R`
            dirs_status `builtin dirs`
            tput sgr0
            ;;
        1)
            printf $1
            ;;
        *)
            tput sgr0; tput setaf 3
            for x
            do
                printf " $x"
            done
            ;;
    esac
}

# dirs_status () {
#     local dirs
#     tput bold; tput setaf 3
#     builtin dirs | awk "{
#         printf \"%s\", \$1
#         if (NF > 1) {
#             printf \"`tput sgr0; tput setaf 3`\"
#             for (i=2; i<=NF; i++) printf \" %s\", \$i
#         }
#     }"
#     tput sgr0
#     print
# }