#@IgnoreInspection BashAddShebang
# -*- mode: shell-script; compile-command: (concat "zcompile " buffer-file-name); outline-regexp: "^[\t ]*#[\t ]+[^=]\\|^# +\\|^[\t ]*..." -*-

# This script is run by login shells. It should be used to set the terminal type and run a series of external commands
# (fortune, msgs, etc). Not the place for alias definitions, options, env vars, etc.: it should not change the shell
# environment at all.
#
# 1) All:         /etc/zshenv,       $ZDOTDIR/.zshenv
# 2) Interactive: /etc/zshrc,        $ZDOTDIR/.zshrc
# 3) Login:       /etc/zlogin,       $ZDOTDIR/.zlogin
# ...
# 4) Login:       $ZDOTDIR/.zlogout, /etc/zlogout


# ========
# ======== Profiling
source ~pschaaf/bin/profile.zsh


# ========
# ======== Terminal Settings
export TERM=xterm-256color
stty start ''   stop   ''

zrecompile ~/.zshenv ~/.zlogin ~/.zshrc
inCygwin && zrecompile ~/etc/rc/zshenv.cygwin

if (( $#inIntelliJ )); then
    SHLVL=0
else
    if inMacOS; then
        # in MacOS every shell is a login shell, so only show this for remote connections
        (( $#CONNECTION )) && neofetch --config ~/etc/rc/neofetchrc 2> /dev/null

        # echo move to upper left then resize terminal -- see https://invisible-island.net/xterm/ctlseqs/ctlseqs.html
        printf '\e[3;0;0;1t\e[8;142;100t'
    else
        neofetch --config ~/etc/rc/neofetchrc 2> /dev/null
    fi
fi

set +x
unset trace
typeset -p PATH