#!/bin/sh

PATH=$CYGPATH:$PATH

#sysresources=/etc/X11/xinit/.Xresources
#userresources="$HOME"/.Xresources

# sysmodmap=/etc/X11/xinit/.Xmodmap
# usermodmap="$HOME"/.Xmodmap

# merge in defaults and keymaps
#[ -f "$sysresources" ]  && xrdb -merge "$sysresources"
#[ -f "$userresources" ] && xrdb -merge "$userresources"
# [ -f "$sysmodmap" ]     && xmodmap "$sysmodmap"
# [ -f "$usermodmap" ]    && xmodmap "$usermodmap"

# Start some programs
# run xlogo &
# /bin/sh -c 'xrescreen &'
# screen -wipe
# ~/bin/xrescreen &
run xterm -name xscreen -e 'screen -R -DD' &
run /usr/bin/emacs -rv &
sleep 9999d
#run xterm -name xscreen -e 'screen -R -DD' &

# echo '### '$0 is sleeping for 5...; sleep 5
