# -*- outline-regexp: "^[\t ]*#[\t ]+[^=]\\|^# +\\|^[\t ]*..." -*-

# ****** WARNING: This file is automatically generated. ****** 
# ******          Edits may be overwritten at any time! ****** 

# Built:	Wed Sep 22 22:19:19 PDT 2004
# By:  	pschaaf@copernicus
# For:
#    host     = ramsesii     shell    = /usr/bin/zsh
#    uname    = CYGWIN       term     = xterm     

if [ -n "$PS1" ]; then
interactive=true
fi
prependToList () {
	local each var=$1; shift
if [ "$var" = "CLASSPATH" ]; then
				for each; do
			member $each $var || eval "$var=\"$each\${$var:+;\$$var}\""
		done
	else
for each; do
			member $each $var || eval "$var=\"$each\${$var:+:\$$var}\""
		done
	fi
}

appendToList () {
	local each var=$1; shift
if [ "$var" = "CLASSPATH" ]; then
				for each; do
			member $each $var || eval "$var=\"\${$var:+\$$var;}$each\""
		done
	else
for each; do
			member $each $var || eval "$var=\"\${$var:+\$$var:}$each\""
		done
	fi
}

_prependToList () {
	local each var=$1; shift
if [ "$var" = "CLASSPATH" ]; then
				for each; do
			eval "$var=\"$each\${$var:+;\$$var}\""
		done
	else
for each; do
			eval "$var=\"$each\${$var:+:\$$var}\""
		done
	fi
}

_appendToList () {
	local each var=$1; shift
if [ "$var" = "CLASSPATH" ]; then
				for each; do
			eval "$var=\"\${$var:+\$$var;}$each\""
		done
	else
for each; do
			eval "$var=\"\${$var:+\$$var:}$each\""
		done
	fi
}

prependToVar () {
	local var=$1; shift; eval "$var=$*\${$var}"
}

appendToVar () {
	local var=$1; shift; eval "$var=\${$var}$*"
}

export HOSTNAME=ramsesii
echoVar () {
	
      local var
      for var
      do
        eval echo -E $var=\\\'\$$var\\\'
      done
}

member () {
	eval echo :"\$$2": | grep ":$1:" >&/dev/null
}

rmpath () {
	PATH=`echo :$PATH | sed "s~:$1~~; s~^:~~"`
}

setenv () {
	local _label=$1; shift; export $_label="$@"
}

exportDefault () {
	eval : \${$1:='$2'}; export $1
}

removeFromList () {
	local each var=$1; shift
	  for each; do
	    eval "$var=\"\${$var//:\$each:/:}\""
          done
}

typeset -U CDPATH FPATH MANPATH PATH
# set -x
# ======== umask
# This umask gives these access permissions:
# user=rwx, group=rx, others=rx
umask 22

# ======== Fix the Path
# echo a path without double slashes, or empty or relative paths
cleanpath () {
	echo :$PATH: | sed 's/:::*/:/g; s/:[^/][^:]*//g; s/^://; s/:$//'
}

# ======== Terminal Settings
if [ "$TERM" = "screen" ]; then
fi
if [ -n "$interactive" ]; then
: stty eol '^-' werase '^W' eol2 '^-' erase '^H' eof '^D' start '^Q' intr '^C' rprnt '^R' time '0' lnext '^V' stop '^S' quit '^\\' min '1' flush '^O' susp '^Z' kill '^U' 
fi
# ======== Colors
if [ -n "$interactive" ]; then
if [ "$TERM" != "emacs" ]; then
export USE_COLOR=true
fi
fi
# ======== Unalias
unalias l la ll ls lsd rm d s p rd 2>/dev/null
# ======== Default Settings

# ======== Shell Options
setopt no_hup
setopt ignore_eof
setopt no_clobber
setopt nonotify
setopt no_beep
bindkey -e
limit coredumpsize 0
unsetopt rm_star_silent
unsetopt print_exit_value
# ======== Completion, Hashing
if [ -n "$interactive" ]; then
setopt hash_cmds hash_dirs
setopt auto_list auto_menu auto_param_slash auto_remove_slash
export FIGNORE=.class:.o:\~:.stackdump:dump.txt:nohup.out
setopt   correct; alias mv='nocorrect mv'; alias cp='nocorrect cp'
fi
# ======== Zsh Compinstall
if [ -n "$interactive" ]; then

zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' file-sort name
zstyle ':completion:*' group-name ''
zstyle ':completion:*' ignore-parents parent ..
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt '%SAt %p: Hit TAB for more, or the character to insert%s'
zstyle ':completion:*' menu select=0
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle ':completion:*' squeeze-slashes true
zstyle ':zftp:' titlebar true
zstyle ':completion:*' verbose true
zstyle  :compinstall filename "$HOME/etc/env/ramsesii.zsh"

autoload -U compinit
compinit -u
autoload zed
alias fned='zed -f'
unalias run-help 2>/dev/null
autoload run-help
export HELPDIR=$HOME/local/sync/zsh_help
fi
# ======== Cd, Dirs, Popd, Pushd
if [ -n "$interactive" ]; then
setopt auto_pushd


setopt pushd_silent pushd_to_home
pushd () {
	# if target is a file, change to its location
         if [ -f $1 ]; then
           builtin pushd $1:h > /dev/null
         else
           builtin pushd $1 > /dev/null
         fi
         
}

fi
# ======== Shell History
if [ -n "$interactive" ]; then
setopt hist_ignore_dups hist_ignore_space hist_reduce_blanks
setopt hist_find_no_dups
export HISTSIZE=1000
setopt extended_history
setopt bang_hist
setopt inc_append_history
setopt hist_no_functions
setopt function_argzero
fi
# ======== Aliases
if [ -n "$interactive" ]; then
any_alias () {
	local label=$1; shift; alias $label="$*"
}

alias basename='collect command\ basename'
alias call=''
alias createdb='$VERSANT_ROOT/bin/createdb'
dirs () {
	builtin dirs ${*:--p}
}

alias dirname='collect command\ dirname'
alias df >& /dev/null || alias df='df -h -x supermount'
alias du >& /dev/null || alias du='du -h'
alias ECHO='echo'
alias EHCO='echo'
alias ehco='echo'
alias freshen='source ~/'
alias igrep='grep -i'
alias jpegthumb='jegscale 128 $*'
alias less='/usr/bin/less'
export PAGER=/usr/bin/less
alias pstree='pstree -G'
alias rm='rm -i'
alias which-command='path'
alias visudo='EDITOR=xemacs visudo'
fi
# ======== Clearcase Aliases
# ======== ls Aliases
export LS_BIN=ls
alias l='$LS_BIN'
export LS_COLORS="no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:bd=40;33;01:cd=40;33;01:or=01;05;37;41:mi=01;05;37;41:ex=01;32:*.btm=01;32:*.tar=01;31:*.tgz=01;31:*.tbz2=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lha=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.bz=01;31:*.tz=01;31:*.rpm=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.xbm=01;35:*.xpm=01;35:*.png=01;35:*.tif=01;35:*.tiff=01;35"
export LS_COLORS="$LS_COLORS:*.bat=01;32:*.cmd=01;32:*.com=01;32:*.exe=01;32"
export LA_FLAGS='-ACFb --color=always --ignore HKEY_PERFOMANCE_DATA --ignore hiberfil.sys --ignore nohup.out --ignore pagefile.sys'
export LS_FLAGS='-BCFb --color=always --ignore HKEY_PERFOMANCE_DATA --ignore hiberfil.sys --ignore nohup.out --ignore pagefile.sys'
export LL_FLAGS='-BCFbhl --color=always --ignore HKEY_PERFOMANCE_DATA --ignore hiberfil.sys --ignore nohup.out --ignore pagefile.sys'
alias la='ls -ACFb --color=always --ignore HKEY_PERFOMANCE_DATA --ignore hiberfil.sys --ignore nohup.out --ignore pagefile.sys'
alias ls='ls -BCFb --color=always --ignore HKEY_PERFOMANCE_DATA --ignore hiberfil.sys --ignore nohup.out --ignore pagefile.sys'
alias ll='ls -BCFbhl --color=always --ignore HKEY_PERFOMANCE_DATA --ignore hiberfil.sys --ignore nohup.out --ignore pagefile.sys'
alias lr='ls -R'
alias lla='la -l'
alias llt='ll -rt'
lld () {
	ll  $* | grep --color=never "/$\\|^$\\|^[^ ][^ ]*$"
}

lltt () {
	llt $* | grep "date +%b.%d"
}

lsd () {
	        for x in ${*:-.}
        do
            pushd $x
            ls -BCbd --color=always --ignore HKEY_PERFOMANCE_DATA --ignore hiberfil.sys --ignore nohup.out --ignore pagefile.sys */
	    popd
        done
}

lsda () {
	        for x in ${*:-.}
        do
            pushd $x
            ls -BCabd --color=always --ignore HKEY_PERFOMANCE_DATA --ignore hiberfil.sys --ignore nohup.out --ignore pagefile.sys */ .*/
	    popd
        done
}

alias lsad='lsda'
lsf () {
	local x
        for x in ${*:-*}
        do
          echo `file -N -F: -- $x`:`ls -d -- $x` | sed 's/^[^:]*: //'
        done | column -t -s ':'
}

# ======== Path Functions
if [ -n "$interactive" ]; then
classpath () {
	echo Examining \$\$\(cygpath\ \-aup\ \$CLASSPATH\); echo; echoList $(cygpath -aup $CLASSPATH) $*
}

fpath () {
	echo Examining \$FPATH; echo; echoList $FPATH $*
}

infopath () {
	echo Examining \$INFOPATH; echo; echoList $INFOPATH $*
}

libpath () {
	echo Examining \$\$LD_LIBRARY_PATH; echo; echoList $LD_LIBRARY_PATH $*
}

manpath () {
	echo Examining \$MANPATH; echo; echoList ${MANPATH:-`man -w`} $*
}

path () {
	local regex="${*// /\|}"
                            whence $* | 
                              sed '/^$\|^\/\|not found$/d; s:^\('$regex'\):[1;40;33m\1[0;0m:g' | pr -rto 2; echo; echoList ${PATH//:\/bin:/:/bin [-> /usr/bin]:} $*
}

fi
appendLibpath () {
	appendToList LD_LIBRARY_PATH $*
}

prependLibpath () {
	prependToList LD_LIBRARY_PATH $*
}

appendManpath () {
	appendToList MANPATH $*
}

prependManpath () {
	prependToList MANPATH $*
}

appendPath () {
	appendToList PATH $*
}

prependPath () {
	prependToList PATH $*
}

appendClasspath () {
	appendToList CLASSPATH $*
}

prependClasspath () {
	prependToList CLASSPATH $*
}

updateManpath () {
	appendManpath `echo $PATH | awk '/\/bin$/ {gsub(/\/bin$/, "/man"); print}' RS=':'`
}

# ======== Functions
cdl () {
	cd $*; ls
}


collect () {
	local cmd x
cmd=$1; shift
for x
do
eval $cmd $x
done
}

ctset () {
	source ~/bin/ctset
}

ddu () {
	find ${*:-.} -type d -maxdepth 1 -exec du -hs {} \; | sort -n
}

echoList () {
	    local list=$1
    shift
    echo $list | sed 's,\(^\|:\)'$HOME',\1~,g' | awk '
    NR == 1 {split(file, files, " ")}

    function output(string) {outstr = outstr string}

    {
      output(sprintf(" %2d ", NR))

      for (idx in files) {
        fullname = " " $1 "/" files[idx]
        if (! system("test -f" fullname)) {
          output("*")
          matches = matches fullname
          break
        }
      }

      output($0 "\n")
    }
    END {
      printf("%s", outstr)
      if (matches) {
        print "\n" cmd matches "\n"
        system("for x in" matches "\ndo\n" cmd " $x\ndone")
      }
    }' RS=: file="$*" cmd="ls $LL_FLAGS" | sed 's/ \*\([^ 	]*\)/[1;33m \1[0m/g'
}

edit () {
	$EDITOR $* &
}

jpegscale () {
	boundary=$1; shift
  for file in $*
  do
    jpegtopnm $file | pnmscale -xysize $boundary $boundary | pnmtojpeg >| ${file/./_$boundary.}
  done
}

lite () {
	egrep -a -C 99999 ${*:-''}
}




route () {
	route ${args:-print}
}

# Save script args in variable to allow access inside script
script () {
	SCRIPT_ARGS="script $*" command script $*
}

setfont () {
	local name
        case $1
        in
          unreadable)
             name=nil2
             ;;
          tiny)
             name=5x7
             ;;
          small)
             name=6x10
             ;;
          medium)
             name=7x13
             ;;
          large)
             name=9x15
             ;;
          huge)
             name=10x20
             ;;
          *)
             name=$1
             ;;
        esac
        echo "]50;$name"
}

signals () {
	echo "   \$signals="; echo $signals | tr " " "
" | cat -n | awk ' {print "    ", $1-1, $2}'  | column
}

startx () {
	/d/Progra~1/Exceed.nt/exceed
}

syncdir () {
	make ${1:+-C $1} -ef ~/etc/makefiles/syncdir.make
}

wcat () {
	cat $(which $*)
}

wcd () {
	cd $(which $1)
}

wedit () {
	local cmd file x
         for x in $*
         do
           file=$(which $x) && cmd="${cmd:-edit} $file" || echo $file
         done
       eval $cmd
}

whence () {
	builtin whence -ac $*
}

winclient () {
	eval command winclient `winlongpath $*`
}

winlongpath () {
	(for x in $*; do
       echo "'`cygpath -am $x`' "
     done) | sed 's-/-\\-g'
     echo
}

winshortpath () {
	(for x in $*; do
       echo "'`cygpath -ams $x`' "
     done) | sed 's-/-\\-g'
     echo
}

wless () {
	$PAGER `which $*` 2>/dev/null || echo ${args} not found
}

if [ "$UID" = "0" ]; then
emacs () {
	command emacs -r -u pschaaf $*
}

fi
if [ "$UID" = "0" ]; then
xemacs () {
	command xemacs -xrm 'Emacs*menubar*Foreground: white' -xrm 'Emacs*menubar*Background: red3' -u pschaaf $*
}

fi
vicdo () {
	eval sudo /bin/su -l vschaaf -- --restricted ${*:+-c "'$*'"}
}

# ======== ssh
# ======== Remote sessions
if [ -n "$SSH_TTY" ]; then
export CONNECTION_COLOR='[1;33m'
export CONNECTION=ssh
elif [ -n "$REMOTEHOST" ]; then
export CONNECTION_COLOR='[1;31m'
export CONNECTION=tlnt
elif [ -n "$SUDO_USER" ]; then
export SUDO_COLOR='[43;30m'
export CONNECTION=sudo
elif [ -n "$REMOTEUSER" ]; then
export CONNECTION_COLOR='[1;31m'
export CONNECTION=tlnt
fi
if [ -n "$CONNECTION" ]; then
CONNECTION_END=' '
fi
# ======== Environment and Shell Variables
export BROWSER=mozclient
export CLHSROOT=file:///usr/local/doc/TechRef/languages/lisp/HyperSpec/
export COLUMNS
if [ -n "$CLEARCASE_ROOT" ]; then
export CTVIEW=`$HOME/bin/getCTView`
if [ -n "$CTVIEW" ]; then
CTVIEW="
[1;35m$CTVIEW[0m"
fi
expr "`oscp -v`" \< "6" > /dev/null && any_alias makedb "makedb -g"
fi
export EDITOR=winclient
case $USER
in
  vschaaf)
    export EMAIL=designer007@excite.com
    ;;
  pschaaf)
    export EMAIL=paul_schaaf@yahoo.com
    ;;
  root)
    export EMAIL=paul_schaaf@yahoo.com
    ;;
esac
if [ "$USER" = "pschaaf" ]; then
export ESHELL=`$HOME/bin/pref_shell`
else
export ESHELL=$SHELL
fi
export ENSCRIPT='-M letter'
EXIT=exit
export FCEDIT=zed
export GREP_COLOR="[1;33"
export GREP_OPTIONS=--color
export LESS=' --RAW-CONTROL-CHARS --hilite-unread --ignore-case --jump-target=2 --no-init --quit-at-eof --quit-if-one-screen --status-column -Ps%dt/%D ?f%f::STDIN:$'
export LIBPATH_NAME=LD_LIBRARY_PATH
export MAKE_MODE=unix
export OFFICE_DRIVE=D:
export OFFICE_PATH="Program Files//Microsoft Office//Office"
exportDefault SCREENDIR $HOME/tmp
if [ -n "$SCRIPT_ARGS" ]; then
export SCRIPTING_MSG='[cc] '
fi
export SHELL=/usr/bin/zsh
export UNAME=CYGWIN
if [ -n "$EDITOR" ]; then
export VISUAL=$EDITOR
fi
# Any punctuation char in WORDCHARS is considered a part of the adjacent word.
export WORDCHARS='*_-~\$%^'
# The remaining punctuation chars are considered separate words, regardless of what may be adjacent:
# 	!"#&'()+,./:;<=>?@[]`{|}

# ======== Printers
export PRINTER=lj1
export MOZ_PRINTER_NAME=$PRINTER
# ======== Cygwin Path
   #if_defined('__PWD')
     # Perhaps win could not successfully change to this dir,
     # e.g. it is a UNC path. We must get there ourselves.
     #eval cd $(ruby -e "puts Regexp.escape(ENV['__PWD'].gsub('-', '__MINUS__')).gsub('__MINUS__', '-')")
   #shell_endif
   #if there are spaces in pwd, convert to short (mangled) path
   if [ `expr $PWD : '.* '` -gt 0 ]; then
     cd $(cygpath -u $(cygpath -asw "$PWD"))
   fi
   unset __PWD

   appendPath /bin
# ======== Function Keys
bindkey "[17~" kill-whole-line	# F6 cut
bindkey "[18~" copy-region-as-kill	# F7 copy
bindkey "[19~" yank	# F8 paste
bindkey "[20~" history-incremental-search-backward	# F9 search
if [ -z "$inScreen" ]; then
bindkey -s "[24~" "exit\n"	# F12 exit
fi
# ======== Cursor Keys
bindkey "\033[1;5D" backward-word	# ctrl_left
bindkey "\033[1;5C" forward-word	# ctrl_right
# ======== Other Extra Keys
bindkey "\033[3~" delete-char	# delete
bindkey "\033[4~" end-of-line	# end
bindkey "\033[1~" beginning-of-line	# home

bindkey "\033^È" undo	# alt_backspace

# ======== Macro Keys
bindkey -s ""^_"" "\C-apath \C-e\C-m"	# C-? prepends 'whence' to command line
# ======== Lesskey
export LESSKEY=/home/pschaaf/.less_ramsesii
# ======== Classpath
# ======== Path
prependPath /bin /usr/bin /usr/local/bin /usr/local/bin/i686-pc-cygwin $HOME/bin/win
appendPath /sbin /usr/sbin $HOME/bin $HOME/bin/usr-local-bin
if [ -n "$VERSANT_ROOT" ]; then
appendPath $HOME/bin/vsnt $(cygpath -au $VERSANT_ROOT)\\bin
exportDefault VERSANT_DB $(cygpath -aw $(dirname $(cygpath -au $VERSANT_ROOT))/db)
exportDefault VERSANT_DBID $VERSANT_DB
exportDefault VERSANT_DBID_NODE ramsesii
fi
# ======== Library Path
appendLibpath /lib /usr/lib $HOME/lib
# ======== Prompt
if [ -n "$interactive" ]; then
case $TERM
in
emacs)
	
chpwd () {
	local dirs
       dirs="`builtin dirs  |
       awk 'NR == 2 {printf("%s", "")}
            {print}' ORS=' '`"
PS1="$CTVIEW
%{%(!.[41;1;37m.)%}%T %{[1;7;32m%}%n@%{[1;7;32m%}ramsesii %64>\>>$dirs%<<
%2(L.%L-.)%{k\%(!.[41;1;37m.)%}%! %{$CONNECTION_COLOR%}$CONNECTION$CONNECTION_END$SCRIPTING_MSG%(!.#.$) "
}

PS2="(%_) %(!.#.$) "
;;
*)
	
chpwd () {
	local dirs
       dirs="`builtin dirs  |
       awk 'NR == 2 {printf("%s", "[0;33m")}
            {print}' ORS=' '`"
PS1="$CTVIEW
%{%(!.[41;1;37m.[0m)%}%T%{[0m%} %{[1;7;32m%}%n@%{[1;7;32m%}ramsesii%{[0m%} %{[1;33m%}%64>\>>$dirs%<<%{[0m%}
%2(L.%L-.)%{k\%(!.[41;1;37m.[1;36m)%}%!%{[0m%} %{$CONNECTION_COLOR%}$CONNECTION%{[0m%}$CONNECTION_END$SCRIPTING_MSG%(!.#.$) "
}

PS2="(%{[1;35m%}%_%{[0m%}) %(!.#.$) "
;;
esac

chpwd
fi
# ======== Cygwin
fixpath () {
	local name=$1; local value=$2
        if [ $value ]; then
           export $name=$(cygpath -au $value)
        fi
}

if [ "$SHLVL" = "1" ]; then
export PATH=`echo $PATH | sed 's~:/cygdrive~:~g'`
fixpath ANT_HOME $ANT_HOME
fixpath JAVA_HOME $JAVA_HOME
fixpath WL_HOME $WL_HOME
fixpath VERSANT_PATH $VERSANT_PATH
hash cmd
fi
# ======== Manpath

# Move this heredoc around in the file to temporarily disable sections
# of code. Make sure to keep the opening tag first, and the closing tag
# against the left margin on a line by itself. Don't forget that any
# edits are lost if this file is re-generated.
# : <<DEBUG_NO_EXEC
# DEBUG_NO_EXEC
# 

# Used packages: 
#	emacs		gnuclient	grep_color	grep_gnu	info
#	less		ls_color	ls_gnu		msoffice	screen
#	versant		vi		vim		winclient	xemacs
