#!/bin/zsh

# Uncomment the following two lines for normal desktop:
#unset SESSION_MANAGER
#exec /etc/X11/xinit/xinitrc

#twm &

# NOTE: can change behavior based upon $VNCDESKTOP

# exec zsh -il EOF
[ -r $HOME/.Xresources ] && xrdb -merge $HOME/.Xresources
eval `ssh-agent &`
xterm -name xscreen -e 'screen -R -DD' &
emacs -q -r -l /home/pschaaf/.xemacs/init.el &
startkde
vncserver -kill $DISPLAY
# EOF
