#!/bin/zsh

pushd ~/Box\ Sync/Infocom
local stories=".*/${1:-.*}\\.dat\$"
if [[ "$*" = "" ]]; then
    # if no args, show all game files
    find . -regex $stories -print | sed 's/^\.\//  /; s/\.dat$//' | sort
else
    # otherwise run the one requested
    local story=`find . -maxdepth 1 -regex $stories -print -quit`
    story=${story#./}
    echo Story is $story
    if [[ -f ${story} ]]; then
        dir=${story%%.*}
        mkdir $dir
        builtin cd $dir
        command frotz ../$story
        builtin cd ..
        rmdir $dir 2>/dev/null // remove only if empty
    else
        echo Cannot find story "$story"
    fi
fi
popd
