#!/bin/zsh

if [[ $# -eq 0 ]]; then
    command ls ${LS_FLAGS/F/} -ld */(D)
else
    for dir in ${*}; do
        echo
        ls -d $dir
        command ls ${LS_FLAGS/F/} -ld ${dir}/*/(D)
    done
fi
