#!/bin/zsh

switches=()
while [ -n "$*" ]; do
    case $1 in
        -*)
            switches=($switches $1)
            ;;
        *)
            break
            ;;
    esac
    shift
done

local files=${*}
if [[ -z "$files" ]]; then
    files=(~/.zshenv ~/.zlogin ~/.zshrc)
fi

for src in $files; do
    local compiled=${src}.zwc
    if [[ ! -s ${src} ]]; then
        echo ${0:t}: Can\'t open file ${src}
        return 1
    elif [[ ! -s ${compiled} || ${src} -nt ${compiled} ]]; then
        zcompile ${switches} ${src} && echo -n Recompiled ${src}
        if [[ "$src" =~ ".zshenv$" ||  "$src" =~ ".zshrc$" || "$src" =~ ".zlogin$" ]]; then
            echo ". \e[101mLog in again to use the new version.\e[0m"
        else
            echo
        fi
    fi
done
