#!/bin/zsh
# shellcheck disable=SC2168 # "local" only valid in functions

local switches=()
while [[ -n "$*" ]]; do
   case $1 in
      -*)
         switches=(${switches[@]} ${1})
         ;;
      *)
         break
         ;;
   esac
   shift
done

local files=(${@})
if [[ $#files -eq 0 ]]; then
   files=(~/.zshenv ~/.zlogin ~/.zshrc)
fi

for src in ${files}; do
   if [[ ! -s ${src} ]]; then
      echo ${0:t}: Can\'t open file ${src}
      return 1
   fi
   local compiled=${src}.zwc
   if [[ ! -s ${compiled} || ${src} -nt ${compiled} ]]; then
      zcompile ${=switches} ${src}
      [ -L ${src} ] && src=`readlink ${src}`
      echo "Recompiled ${src}"
   fi
done
