# $Source: e:/MyDocuments/cvsroot/etc/env/Makefile,v $
# $Revision: 1.60 $
# $Date: 2004/05/06 22:40:37 $
# $Author: pschaaf $
# $State: Exp $
# $Name:  $

# bugs: doesn't create ~/.screenrc

UMASK=umask 0022

ifndef RUBYLIB
RUBYLIB_ARGS=-I $HOME/lib/ruby -I$HOME/bin 
endif

ifdef CYGROOT
NICE_MAKE=${MAKE}
USE_THREADS=

# Ignore warnings about insecure directories under Cygwin
RUBY_SWITCHES=-W$${RUBY_WARN_LEVEL:=0}

else
NICE_MAKE=nice --adjustment=10 ${MAKE}
USE_THREADS=
#-j 2
endif

RUBY=ruby ${RUBY_SWITCHES} ${RUBYLIB_ARGS}

SHELLS_MAKEFILE=.shells.make
SHELLS_MAKEFILE_MAKER=make_shells.rb

MAKE=${UMASK}; ${SET_RUBYLIB} make

UNAME=$(subst _NT-5.0,,$(shell uname))
.SUFFIXES:

DOMAINNAME=$(shell domainname)
HOSTNAME=$(subst .$(DOMAINNAME),,$(shell hostname))
ALL_HOSTS=$(shell hosts) generic
ALL_SHELLS=$(foreach x,${ALL_HOSTS},$(addprefix ${x},.bash .csh .ksh .screen .sh .zsh))

.PHONY:	$(HOSTNAME) chmod test every_host
RC_ENTRY_POINT=$(shell if [ "$(DOMAINNAME)" = "versant.com" ] && [ "$(UNAME)" != "CYGWIN" ]; \
	then echo resolve_local; \
	else echo $(HOSTNAME); \
	fi)

LINKS=${HOME}/.zprofile ${HOME}/.zshrc $(if ${CYGROOT},,${HOME}/.bash_profile ${HOME}/.tcshrc) resolve_local.bash resolve_local.tcsh resolve_local.zsh
# ${HOME}/.bashrc


all:	localhost every_host links ${UNAME} removeBackups TAGS

removeBackups:
	-@rm -f *~ .*~ nohup.out
	-find -type f -empty ! -name '.*' -exec rm -f {} \;

clean:	removeBackups
	if [ -e ${SHELLS_MAKEFILE} ]; then ${MAKE} -f ${SHELLS_MAKEFILE} clean; fi
	for x in `hosts`; do rm -f $$x.*; done
	rm -f ${SHELLS_MAKEFILE} ${LINKS}
	@echo

rebuild:	clean all

TAGS:	${SHELLS_MAKEFILE_MAKER} Makefile *.rb
	@echo; echo === Regenerating $@ file due to changes in:
	@echo '    '$?
	etags $^

localhost:	${HOSTNAME}

${ALL_HOSTS} every_host:	${SHELLS_MAKEFILE}

${ALL_HOSTS} ${ALL_SHELLS} deploy:
	${MAKE} -sf ${SHELLS_MAKEFILE} $@

every_host:
	${MAKE} -sf ${SHELLS_MAKEFILE} all
#	${NICE_MAKE} ${USE_THREADS} -f ${SHELLS_MAKEFILE}

${SHELLS_MAKEFILE}:	${SHELLS_MAKEFILE_MAKER} contacts.rb keyboard.rb port.rb servers.rb host.rb screenrc.rb shellrc.rb
	${RUBY} ./${SHELLS_MAKEFILE_MAKER} $@

${SHELLS_MAKEFILE_MAKER}:

chmod:
	-@find -path './CVS' -prune -o -maxdepth 1 \( -type f ! -perm 644 -exec chmod 644 {} \; -o -type d ! -perm 755 -exec chmod 755 {} \; \) -printf "Fixed permissions of %p\n"

# ####### links
links:	${LINKS}

${LINKS}:
	ln -fs ${PWD}/$? $@

${HOME}/.bash_profile:	login.bash
${HOME}/.bashrc:	$(RC_ENTRY_POINT).bash
${HOME}/.tcshrc:	$(RC_ENTRY_POINT).tcsh
${HOME}/.zshrc:	$(RC_ENTRY_POINT).zsh

resolve_local.bash resolve_local.zsh:	resolve_local.sh
resolve_local.tcsh:	resolve_local.csh

# ####### uname
CYGWIN:
	@echo; echo === CYGWIN: \(Re\)setting hidden flag on files that would be automatically hidden by Unix.
	-@cd; attrib +H '.*' # this won't affect directories without appending '/D /S', which also makes it recursive. Windows sucks. :(

Linux:	chmod

# ####### test
debug:
	@echo HOSTNAME=${HOSTNAME}
	@echo DOMAINNAME=${DOMAINNAME}
	@echo RC_ENTRY_POINT=${RC_ENTRY_POINT}
	@echo SHELLS_MAKEFILE=${SHELLS_MAKEFILE}
	@echo SHELLS_MAKEFILE_MAKER=${SHELLS_MAKEFILE_MAKER}
	@echo RUBY=${RUBY}
	@echo RUBYLIB_DEFAULT=${RUBYLIB_DEFAULT}
	@echo HOME=${HOME}
	@echo CYGROOT=${CYGROOT}
	@echo SUBMAKE_SWITCHES=${SUBMAKE_SWITCHES}
	@echo ALL_SHELLS=${ALL_SHELLS}
