default:	msie/guidewire_application_lo.user.js

all:	chrome/craigslist_auto-poster/craigslist_auto-poster.user.js msie/guidewire_application_lo.user.js

chrome/craigslist_auto-poster/craigslist_auto-poster.user.js:	craigslist_auto-poster.user.js
	@echo Publishing $? to $(dir $@)
	@cp $? $@

msie/guidewire_application_lo.user.js:	guidewire_application_lo.user.js
	@echo Publishing $? to $(dir $@)
	@cp $? $@

chrome/yj/yj.user.js:	yj.user.js
	@echo Publishing $? to $(dir $@)
	@cp $? $@
